// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: pkg/pb/node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRole int32

const (
	NodeRole_UNKNOWN_ROLE NodeRole = 0
	NodeRole_WRITERM      NodeRole = 1 // Master Writer
	NodeRole_WRITERB      NodeRole = 2 // Backup Writer
	NodeRole_READER       NodeRole = 3 // Reader
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "UNKNOWN_ROLE",
		1: "WRITERM",
		2: "WRITERB",
		3: "READER",
	}
	NodeRole_value = map[string]int32{
		"UNKNOWN_ROLE": 0,
		"WRITERM":      1,
		"WRITERB":      2,
		"READER":       3,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_node_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_pkg_pb_node_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_node_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_UNKNOWN_STATUS NodeStatus = 0
	NodeStatus_SYNCED         NodeStatus = 1 // Blockchain data up-to-date, only for Writer node
	NodeStatus_SYNCING        NodeStatus = 2 // Blockchain date out-of-date, only for Writer node
	NodeStatus_UNHEALTHY      NodeStatus = 3 // Internal unhealthy, either Reader or Writer
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "SYNCED",
		2: "SYNCING",
		3: "UNHEALTHY",
	}
	NodeStatus_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"SYNCED":         1,
		"SYNCING":        2,
		"UNHEALTHY":      3,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_node_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_pkg_pb_node_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_node_proto_rawDescGZIP(), []int{1}
}

type BlockUpdateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum  int64  `protobuf:"varint,4,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	BlockHash string `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (x *BlockUpdateInfo) Reset() {
	*x = BlockUpdateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUpdateInfo) ProtoMessage() {}

func (x *BlockUpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUpdateInfo.ProtoReflect.Descriptor instead.
func (*BlockUpdateInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_node_proto_rawDescGZIP(), []int{0}
}

func (x *BlockUpdateInfo) GetBlockNum() int64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

func (x *BlockUpdateInfo) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

type NodeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Env             string           `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`                        // 环境
	ChainId         string           `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"` // 对应chain的id
	Role            NodeRole         `protobuf:"varint,3,opt,name=role,proto3,enum=pb.NodeRole" json:"role,omitempty"`
	Uuid            string           `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                // 机器唯一标识
	Endpoint        string           `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                        // 机器ip:port
	BlockUpdateInfo *BlockUpdateInfo `protobuf:"bytes,6,opt,name=block_update_info,json=blockUpdateInfo,proto3" json:"block_update_info,omitempty"` // 最新区块信息
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_pkg_pb_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeId) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *NodeId) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *NodeId) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_UNKNOWN_ROLE
}

func (x *NodeId) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *NodeId) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NodeId) GetBlockUpdateInfo() *BlockUpdateInfo {
	if x != nil {
		return x.BlockUpdateInfo
	}
	return nil
}

var File_pkg_pb_node_proto protoreflect.FileDescriptor

var file_pkg_pb_node_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x4d, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x22, 0xc8, 0x01, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x6e, 0x76, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x3f, 0x0a, 0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x2a, 0x42, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a,
	0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x57, 0x52, 0x49, 0x54, 0x45, 0x52, 0x4d, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x57, 0x52, 0x49, 0x54, 0x45, 0x52, 0x42, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x41,
	0x44, 0x45, 0x52, 0x10, 0x03, 0x2a, 0x48, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x4e, 0x43, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x59, 0x4e, 0x43, 0x49, 0x4e, 0x47, 0x10, 0x02,
	0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x48, 0x45, 0x41, 0x4c, 0x54, 0x48, 0x59, 0x10, 0x03, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65,
	0x42, 0x61, 0x6e, 0x6b, 0x44, 0x65, 0x46, 0x69, 0x2f, 0x64, 0x62, 0x2d, 0x72, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_node_proto_rawDescOnce sync.Once
	file_pkg_pb_node_proto_rawDescData = file_pkg_pb_node_proto_rawDesc
)

func file_pkg_pb_node_proto_rawDescGZIP() []byte {
	file_pkg_pb_node_proto_rawDescOnce.Do(func() {
		file_pkg_pb_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_node_proto_rawDescData)
	})
	return file_pkg_pb_node_proto_rawDescData
}

var file_pkg_pb_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_pb_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_node_proto_goTypes = []interface{}{
	(NodeRole)(0),           // 0: pb.NodeRole
	(NodeStatus)(0),         // 1: pb.NodeStatus
	(*BlockUpdateInfo)(nil), // 2: pb.BlockUpdateInfo
	(*NodeId)(nil),          // 3: pb.NodeId
}
var file_pkg_pb_node_proto_depIdxs = []int32{
	0, // 0: pb.NodeId.role:type_name -> pb.NodeRole
	2, // 1: pb.NodeId.block_update_info:type_name -> pb.BlockUpdateInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_node_proto_init() }
func file_pkg_pb_node_proto_init() {
	if File_pkg_pb_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockUpdateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_node_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_pb_node_proto_goTypes,
		DependencyIndexes: file_pkg_pb_node_proto_depIdxs,
		EnumInfos:         file_pkg_pb_node_proto_enumTypes,
		MessageInfos:      file_pkg_pb_node_proto_msgTypes,
	}.Build()
	File_pkg_pb_node_proto = out.File
	file_pkg_pb_node_proto_rawDesc = nil
	file_pkg_pb_node_proto_goTypes = nil
	file_pkg_pb_node_proto_depIdxs = nil
}
