// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: pkg/pb/subscribe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriterEvent int32

const (
	WriterEvent_UNKNOWN_WRITE_EVENT WriterEvent = 0
	WriterEvent_ROLE_CHANGED        WriterEvent = 1
	WriterEvent_OUT_OF_SYNC         WriterEvent = 2
)

// Enum value maps for WriterEvent.
var (
	WriterEvent_name = map[int32]string{
		0: "UNKNOWN_WRITE_EVENT",
		1: "ROLE_CHANGED",
		2: "OUT_OF_SYNC",
	}
	WriterEvent_value = map[string]int32{
		"UNKNOWN_WRITE_EVENT": 0,
		"ROLE_CHANGED":        1,
		"OUT_OF_SYNC":         2,
	}
)

func (x WriterEvent) Enum() *WriterEvent {
	p := new(WriterEvent)
	*p = x
	return p
}

func (x WriterEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriterEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_pb_subscribe_proto_enumTypes[0].Descriptor()
}

func (WriterEvent) Type() protoreflect.EnumType {
	return &file_pkg_pb_subscribe_proto_enumTypes[0]
}

func (x WriterEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriterEvent.Descriptor instead.
func (WriterEvent) EnumDescriptor() ([]byte, []int) {
	return file_pkg_pb_subscribe_proto_rawDescGZIP(), []int{0}
}

type WriterEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event  WriterEvent `protobuf:"varint,1,opt,name=event,proto3,enum=pb.WriterEvent" json:"event,omitempty"`
	Leader *NodeId     `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
}

func (x *WriterEventResponse) Reset() {
	*x = WriterEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_subscribe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriterEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriterEventResponse) ProtoMessage() {}

func (x *WriterEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_subscribe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriterEventResponse.ProtoReflect.Descriptor instead.
func (*WriterEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_subscribe_proto_rawDescGZIP(), []int{0}
}

func (x *WriterEventResponse) GetEvent() WriterEvent {
	if x != nil {
		return x.Event
	}
	return WriterEvent_UNKNOWN_WRITE_EVENT
}

func (x *WriterEventResponse) GetLeader() *NodeId {
	if x != nil {
		return x.Leader
	}
	return nil
}

type WriterEventSubcribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout int64 `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"` // optional, watch timeout, watch permanently if timeout is zero.
}

func (x *WriterEventSubcribeRequest) Reset() {
	*x = WriterEventSubcribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_subscribe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriterEventSubcribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriterEventSubcribeRequest) ProtoMessage() {}

func (x *WriterEventSubcribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_subscribe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriterEventSubcribeRequest.ProtoReflect.Descriptor instead.
func (*WriterEventSubcribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_subscribe_proto_rawDescGZIP(), []int{1}
}

func (x *WriterEventSubcribeRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ListReaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListReaderRequest) Reset() {
	*x = ListReaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_subscribe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReaderRequest) ProtoMessage() {}

func (x *ListReaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_subscribe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReaderRequest.ProtoReflect.Descriptor instead.
func (*ListReaderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_subscribe_proto_rawDescGZIP(), []int{2}
}

type ListReaderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Readers []*NodeId `protobuf:"bytes,1,rep,name=readers,proto3" json:"readers,omitempty"`
}

func (x *ListReaderResponse) Reset() {
	*x = ListReaderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_subscribe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListReaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReaderResponse) ProtoMessage() {}

func (x *ListReaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_subscribe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReaderResponse.ProtoReflect.Descriptor instead.
func (*ListReaderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_subscribe_proto_rawDescGZIP(), []int{3}
}

func (x *ListReaderResponse) GetReaders() []*NodeId {
	if x != nil {
		return x.Readers
	}
	return nil
}

var File_pkg_pb_subscribe_proto protoreflect.FileDescriptor

var file_pkg_pb_subscribe_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x11, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x60, 0x0a, 0x13, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a,
	0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x22, 0x36, 0x0a, 0x1a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x2a, 0x49, 0x0a, 0x0b, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x53,
	0x59, 0x4e, 0x43, 0x10, 0x02, 0x32, 0xa2, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x10, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1e,
	0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x75, 0x62, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x0a, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x44,
	0x65, 0x46, 0x69, 0x2f, 0x64, 0x62, 0x2d, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x6f,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_subscribe_proto_rawDescOnce sync.Once
	file_pkg_pb_subscribe_proto_rawDescData = file_pkg_pb_subscribe_proto_rawDesc
)

func file_pkg_pb_subscribe_proto_rawDescGZIP() []byte {
	file_pkg_pb_subscribe_proto_rawDescOnce.Do(func() {
		file_pkg_pb_subscribe_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_subscribe_proto_rawDescData)
	})
	return file_pkg_pb_subscribe_proto_rawDescData
}

var file_pkg_pb_subscribe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_pb_subscribe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_pb_subscribe_proto_goTypes = []interface{}{
	(WriterEvent)(0),                   // 0: pb.WriterEvent
	(*WriterEventResponse)(nil),        // 1: pb.WriterEventResponse
	(*WriterEventSubcribeRequest)(nil), // 2: pb.WriterEventSubcribeRequest
	(*ListReaderRequest)(nil),          // 3: pb.ListReaderRequest
	(*ListReaderResponse)(nil),         // 4: pb.ListReaderResponse
	(*NodeId)(nil),                     // 5: pb.NodeId
}
var file_pkg_pb_subscribe_proto_depIdxs = []int32{
	0, // 0: pb.WriterEventResponse.event:type_name -> pb.WriterEvent
	5, // 1: pb.WriterEventResponse.leader:type_name -> pb.NodeId
	5, // 2: pb.ListReaderResponse.readers:type_name -> pb.NodeId
	2, // 3: pb.SubscribeService.WatchWriterEvent:input_type -> pb.WriterEventSubcribeRequest
	3, // 4: pb.SubscribeService.ListReader:input_type -> pb.ListReaderRequest
	1, // 5: pb.SubscribeService.WatchWriterEvent:output_type -> pb.WriterEventResponse
	4, // 6: pb.SubscribeService.ListReader:output_type -> pb.ListReaderResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_pb_subscribe_proto_init() }
func file_pkg_pb_subscribe_proto_init() {
	if File_pkg_pb_subscribe_proto != nil {
		return
	}
	file_pkg_pb_node_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_subscribe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriterEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_subscribe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriterEventSubcribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_subscribe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_subscribe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListReaderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_subscribe_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_subscribe_proto_goTypes,
		DependencyIndexes: file_pkg_pb_subscribe_proto_depIdxs,
		EnumInfos:         file_pkg_pb_subscribe_proto_enumTypes,
		MessageInfos:      file_pkg_pb_subscribe_proto_msgTypes,
	}.Build()
	File_pkg_pb_subscribe_proto = out.File
	file_pkg_pb_subscribe_proto_rawDesc = nil
	file_pkg_pb_subscribe_proto_goTypes = nil
	file_pkg_pb_subscribe_proto_depIdxs = nil
}
